#!/usr/bin/ruby

if ARGV.length == 0
    puts "This is the ATK command! I'm glad to see you're using it.\nRunning it with no arguments will just get you this message :)"
# if one argument, then act like grep
elsif ARGV.length == 1
# if two arguments, then act like sed
elsif ARGV.length == 2
    # get arguments 
        find        = ARGV[0]
        replacement = ARGV[1]
    # get standard input 
        # gotta clear ARGV before getting stdin 
        ARGV.clear
        input = $stdin.read
end#if 
